### ISSUE TITLE
Translation bot 번역 결과 msg 수정, 의뢰한 문장 수와 포인트 조회

### ISSUE THREAD

**Issue by danbeekim** [psy2848048/translator_api#14]
수정 전
 
LangChain:

Human guided:

Google:

Powered by LangChain

수정 후 

LangChainMachineTranslator:

LangChainTrainerbot: (No results)

Google:

You can train @langchainbot by @LangChainTrainerbot and get Frontier point!  

You’ve entered X sentences. 
You got X points.

Powered by LangChain

**Comment by danbeekim** [comment]
LangChainTrainerbot 결과가 없으면 아예 안떴었는데 (No results) 라고 띄워주는게 좋을것 같아요. trainer 참여 유도도 가능

**Comment by sssunho** [comment]
You’ve entered X sentences. 
는 내가 여태까지 입력한 문장의 개수

You got X points.
는 내가 여태까지 얻은 포인트

**Comment by psy2848048** [comment]
입력한 문장 개수도 getId 같은 곳 응답에 넣어줘야할 듯 하네요

**Comment by sssunho** [comment]
입력한 문장 개수 넣었습니다!
