### ISSUE TITLE
translation bot 로직/msg 수정

### ISSUE THREAD

**Issue by danbeekim** [psy2848048/translator_api#26]
수정전

LangChainMachineTranslator:
그것 은 아름답 ㄴ 날씨 이 었 다 .

LangChainTrainerbot:
None

Google:
정말 멋진 하루 야.

You can train @langchainbot by @LangChainTrainerbot and get Frontier point!

You’ve entered None sentences.
You got 0 points.

Powered by LangChain

수정후

LangChain Machine Translation:
그것 은 아름답 ㄴ 날씨 이 었 다 . 

LangChain Trainerbot:
None

General Translation:
정말 멋진 하루 야.

You can train @langchainbot by @LangChainTrainerbot and get Frontier point!
Powered by LangChain

**Comment by danbeekim** [comment]
최대한 길이가 짧아지게
LangChain Trainerbot: 의 결과값이 있는 경우에는 General Translation: 이 뜨지 않게 수정 부탁드립니다. 
포인트는 삭제되고 트레이너봇 balance를 누르면 볼 수 있도록

**Comment by sssunho** [comment]
- LangChain Trainerbot: 의 결과값이 있는 경우에는 General Translation: 이 뜨지 않게 수정 부탁드립니다.
수정 완료

- 포인트는 삭제되고 트레이너봇 balance를 누르면 볼 수 있도록
You have 33.0 points!
Thanks for your contribution!

en → ko: 15.5 Points
ko → en: 17.5 Points
ko → ja: 0.0 Points
zh → es: 0.0 Points
